---
title: Meaghan McManus
email: meaghan.mcmanus@psychol.uni-giessen.de
author: Meaghan McManus
description:  under construction
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme

---
